"""Idea model — represents a research idea in the AI Scientist pipeline."""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, Field


class IdeaStatus(str, Enum):
    """Status of a research idea."""

    GENERATED = "generated"
    NOVELTY_CHECKED = "novelty_checked"
    SELECTED = "selected"
    REJECTED = "rejected"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"


class Idea(BaseModel):
    """A research idea generated by the AI Scientist."""

    id: str = Field(default_factory=lambda: uuid4().hex[:12])
    title: str
    description: str
    novelty_score: float = Field(default=0.0, ge=0.0, le=10.0)
    feasibility_score: float = Field(default=0.0, ge=0.0, le=10.0)
    impact_score: float = Field(default=0.0, ge=0.0, le=10.0)
    status: IdeaStatus = IdeaStatus.GENERATED
    keywords: list[str] = Field(default_factory=list)
    related_work: list[str] = Field(default_factory=list)
    experiment_plan: str = ""
    metadata: dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

    @property
    def overall_score(self) -> float:
        """Weighted average of novelty, feasibility, and impact."""
        weights = (0.4, 0.3, 0.3)
        scores = (self.novelty_score, self.feasibility_score, self.impact_score)
        return sum(w * s for w, s in zip(weights, scores))


class IdeaGenerationRequest(BaseModel):
    """Request payload for generating research ideas."""

    research_area: str = Field(..., min_length=1, description="Broad research direction")
    num_ideas: int = Field(default=5, ge=1, le=50, description="Number of ideas to generate")
    template: str = Field(default="general", description="Research template to use")
    constraints: list[str] = Field(default_factory=list, description="Additional constraints")


class IdeaGenerationResponse(BaseModel):
    """Response containing generated ideas."""

    ideas: list[Idea]
    generation_time_seconds: float
    model_used: str
