"""Automated peer review service — evaluates generated papers.

Implements the Automated Paper Reviewing phase of the AI Scientist,
providing structured feedback with scores and improvement suggestions.
"""

from __future__ import annotations

import json
import logging
from typing import Any

from langchain_core.messages import HumanMessage, SystemMessage

from app.core.llm_factory import create_chat_model
from app.models.paper import Paper
from app.models.review import Review, ReviewDecision

logger = logging.getLogger(__name__)

_ICLR_REVIEW_PROMPT = """\
You are serving as a Program Committee member for ICLR 2025. Evaluate the following research paper using the official ICLR scoring rubric.

ICLR SCORE DEFINITIONS:
- Overall Score (1-10): 9-10=Outstanding, 7-8=Strong, 5-6=Acceptable, 3-4=Weak, 1-2=Poor
- Confidence (1-5): 5=Absolutely Certain, 4=Very Confident, 3=Confident, 2=Uncertain, 1=Very Uncertain

EVALUATION CRITERIA:

1. TECHNICAL CORRECTNESS & SOUNDNESS (1-5):
   • Mathematically and theoretically correct
   • Proper experimental methodology
   • Validated and reproducible approaches

2. IMPACT & CONTRIBUTION (1-5):
   • Significant advance in the field
   • Novel methodology or insights
   • Addresses important problems

3. CLARITY & PRESENTATION (1-5):
   • Well-written and clear exposition
   • Proper organization and figures
   • Adequate background and context

4. ORIGINALITY (1-5):
   • Truly novel approach or perspective
   • Goes beyond incremental improvements
   • Creative or innovative solution

5. SIGNIFICANCE (1-5):
   • Broader impact on AI/ML community
   • Potential for future research/directions
   • Practical applications

PAPER TO REVIEW:
{paper_text}

Please provide your evaluation AS VALID JSON ONLY with these fields:
{{
    "overall_score": <score_1_to_10>,
    "decision": "accept|reject|borderline", // Decision based on score: 7>=accept, <=4=reject, others=borderline
    "confidence": <1_to_5>,
    "technical_correctness": <1_to_5>,
    "contribution": <1_to_5>,
    "clarity": <1_to_5>,
    "originality": <1_to_5>,
    "significance": <1_to_5>,
    "strengths": ["list", "of", "specific", "strengths"],
    "weaknesses": ["list", "of", "specific", "weaknesses"],
    "questions": ["questions", "for", "authors"],
    "suggestions": ["construction", "suggestions"],
    "revision_required": true|false, // Whether substantial revision is needed
    "accept_as_is": true|false, // Whether minor fixes are sufficient
    "ethical_concerns": ["list", "concerns"],
    "reproducibility_rating": <1_to_5>, // How reproducible the work appears
    "summary": "brief evaluation summary"
}}

Note: Papers scoring 7-10 overall indicate strong acceptance potential; 4-and-below should typically recommend rejection.
"""

_REVIEW_EVALUATION_PROMPT = """\
Based on your initial review and evaluation of the paper, please assign a final acceptance decision considering all criteria.

Your evaluation will determine whether to move through another iteration of experiment refinement 
(if decision="reject" and revision_required=true) or proceed to publication (if acceptance-worthy).

PAPER CONTEXT:
- Generated by AI Scientist pipeline
- Experimental results and code available
- Literature novelty check completed

MAJOR DECISION CATEGORIES:
- ACCEPT: Well-executed, significant contribution, ready for publication
- BORDERLINE: Good work but requires minor-to-moderate revisions
- REJECT: Methodologically flawed, insufficient contribution, or major issues

Return the complete JSON evaluation with your final scores and recommendation.
"""


class Reviewer:
    """Automated peer reviewer for generated papers."""

    def __init__(self) -> None:
        self._llm = create_chat_model()

    def review(
        self,
        paper: Paper,
        num_reflections: int = 5,
        temperature: float = 0.1,
    ) -> Review:
        """Review a generated paper.

        Args:
            paper: The paper to review.
            num_reflections: Number of self-reflection iterations.
            temperature: Sampling temperature for the LLM.

        Returns:
            A ``Review`` with scores and feedback.
        """
        paper_text = self._paper_to_text(paper)
        review = self._single_review(paper_text, paper_id=paper.id)

        # Self-reflection: refine the review
        for i in range(num_reflections - 1):
            review = self._reflect(paper_text, review)

        return review

    def _single_review(self, paper_text: str, paper_id: str = "") -> Review:
        """Generate a single review of the paper using ICLR criteria."""
        review_prompt = _ICLR_REVIEW_PROMPT.format(paper_text=paper_text)
        messages = [
            HumanMessage(content=review_prompt),
        ]

        response = self._llm.invoke(messages)
        return self._parse_review(response.content, paper_id=paper_id)

    def _reflect(self, paper_text: str, previous_review: Review) -> Review:
        """Refine a review through self-reflection and reconsideration according to ICLR process."""
        reflect_prompt = f"""\
Re-evaluate the paper considering your previous assessment:

PREVIOUS EVALUATION:
Overall: {previous_review.overall_score}/10 (Category: {self._get_score_category(previous_review.overall_score)})
Technical Correctness: {getattr(previous_review.metadata, "technical_correctness", 0)}/5
Contribution: {previous_review.contribution}/5
Clarity: {getattr(previous_review.metadata, "clarity", 0)}/5
Originality: {getattr(previous_review.metadata, "originality", 0)}/5
Significance: {getattr(previous_review.metadata, "significance", 0)}/5
Decision: {previous_review.decision.value}

CRITICAL SELF-REFLECTION:
- Did you miss any technical mistakes in your first pass?
- Are the stated contributions accurate or overstated?
- Is the experimental evidence compelling?
- Should the clarity score be adjusted for accessibility?

Consider if any scores should be adjusted based on deeper analysis.

Paper:
{paper_text}

Return a revised JSON evaluation adhering to ICLR standards as before, with potentially refined scorings, strengths, weaknesses, and suggestions."""
        
        messages = [
            SystemMessage(content=_ICLR_REVIEW_PROMPT.format(paper_text=reflect_prompt)),
            HumanMessage(content=_REVIEW_EVALUATION_PROMPT), 
        ]
        response = self._llm.invoke(messages)
        return self._parse_review(response.content, paper_id=previous_review.paper_id)
    
    def _get_score_category(self, score: float) -> str:
        """Convert numerical score to descriptive category."""
        if score >= 8.5:
            return "Outstanding"
        elif score >= 7.0:
            return "Strong"
        elif score >= 5.5:
            return "Acceptable"
        elif score >= 4.0:
            return "Weak"
        else:
            return "Poor"

    def _paper_to_text(self, paper: Paper) -> str:
        """Convert paper to plain text for review."""
        parts = [f"Title: {paper.title}", f"\nAbstract: {paper.abstract}"]
        for section in paper.sections:
            parts.append(f"\n## {section.title}\n{section.content}")
        return "\n".join(parts)

    def _parse_review(self, content: str, paper_id: str = "") -> Review:
        """Parse LLM review output into a Review object."""
        try:
            text = content.strip()
            if "```json" in text:
                text = text.split("```json")[1].split("```")[0]
            elif "```" in text:
                text = text.split("```")[1].split("```")[0]

            data: dict[str, Any] = json.loads(text)
        except (json.JSONDecodeError, IndexError):
            data = {
                "overall_score": 5.0,
                "decision": "borderline",
                "confidence": 3.0,
                "soundness": 2.0,
                "presentation": 2.0,
                "contribution": 2.0,
                "strengths": ["Failed to parse review"],
                "weaknesses": ["LLM output was not valid JSON"],
                "questions": [],
                "suggestions": [],
                "summary": "Review parsing failed; raw output was not structured.",
            }

        # Extract extended fields and pack them into metadata
        extended_metadata = {}
        for key in ["technical_correctness", "clarity", "originality", "significance", 
                   "revision_required", "accept_as_is", "ethical_concerns", "reproducibility_rating"]:
            if key in data:
                extended_metadata[key] = data[key]
        
        # Only update overall_score if it exists in data (otherwise use original)
        overall_score = float(data.get("overall_score", 5.0))
        
        return Review(
            paper_id=paper_id,
            overall_score=overall_score,
            decision=ReviewDecision(data.get("decision", "borderline")),
            confidence=float(data.get("confidence", 3.0)),
            soundness=float(data.get("soundness", 2.0)),
            presentation=float(data.get("presentation", 2.0)),
            contribution=float(data.get("contribution", 2.0)),
            strengths=data.get("strengths", []),
            weaknesses=data.get("weaknesses", []),
            questions=data.get("questions", []),
            suggestions=data.get("suggestions", []),
            summary=data.get("summary", ""),
            metadata=extended_metadata
        )

